const dataArray = {
    "replicaName": "",
    "replicaID": "",
    "transportType": "esriTransportTypeUrl",
    "responseType": "esriReplicaResponseTypeData",
    "replicaServerGen": 1832262088320,
    "layers": [
      {
        "id": 4,
        "features": [
          {
            "attributes": {
              "objectid": 334000,
              "sitecode": "GR4210029",
              "speciescode": "A402",
              "speciesname": "Accipiter brevipes",
              "speciesname_label": "Levant Sparrowhawk - Accipiter brevipes",
              "speciesnameclean": "Accipiter brevipes",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/837/837_869.jpeg&x=300&y=300&a=true",
              "id_eunis": 837,
              "commonname": "Levant Sparrowhawk"
            }
          },
          {
            "attributes": {
              "objectid": 334001,
              "sitecode": "GR4210029",
              "speciescode": "A168",
              "speciesname": "Actitis hypoleucos",
              "speciesname_label": "Common Sandpiper - Actitis hypoleucos",
              "speciesnameclean": "Actitis hypoleucos",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/848/848_878.jpeg&x=300&y=300&a=true",
              "id_eunis": 848,
              "commonname": "Common Sandpiper"
            }
          },
          {
            "attributes": {
              "objectid": 334002,
              "sitecode": "GR4210029",
              "speciescode": "A247",
              "speciesname": "Alauda arvensis",
              "speciesname_label": "Skylark - Alauda arvensis",
              "speciesnameclean": "Alauda arvensis",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing, wintering",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/853/853_883.jpeg&x=300&y=300&a=true",
              "id_eunis": 853,
              "commonname": "Skylark"
            }
          },
          {
            "attributes": {
              "objectid": 334003,
              "sitecode": "GR4210029",
              "speciescode": "A229",
              "speciesname": "Alcedo atthis",
              "speciesname_label": "Kingfisher - Alcedo atthis",
              "speciesnameclean": "Alcedo atthis",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Reproducing, wintering",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/855/855_885.jpeg&x=300&y=300&a=true",
              "id_eunis": 855,
              "commonname": "Kingfisher"
            }
          },
          {
            "attributes": {
              "objectid": 334004,
              "sitecode": "GR4210029",
              "speciescode": "A255",
              "speciesname": "Anthus campestris",
              "speciesname_label": "Tawny Pipit - Anthus campestris",
              "speciesnameclean": "Anthus campestris",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/882/882_10062.jpeg&x=300&y=300&a=true",
              "id_eunis": 882,
              "commonname": "Tawny Pipit"
            }
          },
          {
            "attributes": {
              "objectid": 334005,
              "sitecode": "GR4210029",
              "speciescode": "A226",
              "speciesname": "Apus apus",
              "speciesname_label": "Swift - Apus apus",
              "speciesnameclean": "Apus apus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/888/888_916.jpeg&x=300&y=300&a=true",
              "id_eunis": 888,
              "commonname": "Swift"
            }
          },
          {
            "attributes": {
              "objectid": 334006,
              "sitecode": "GR4210029",
              "speciescode": "A028",
              "speciesname": "Ardea cinerea",
              "speciesname_label": "Grey Heron - Ardea cinerea",
              "speciesnameclean": "Ardea cinerea",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, wintering",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/900/900_923.jpeg&x=300&y=300&a=true",
              "id_eunis": 900,
              "commonname": "Grey Heron"
            }
          },
          {
            "attributes": {
              "objectid": 334007,
              "sitecode": "GR4210029",
              "speciescode": "A169",
              "speciesname": "Arenaria interpres",
              "speciesname_label": "Turnstone - Arenaria interpres",
              "speciesnameclean": "Arenaria interpres",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/904/904_927.jpeg&x=300&y=300&a=true",
              "id_eunis": 904,
              "commonname": "Turnstone"
            }
          },
          {
            "attributes": {
              "objectid": 334008,
              "sitecode": "GR4210029",
              "speciescode": "A133",
              "speciesname": "Burhinus oedicnemus",
              "speciesname_label": "Stone Curlew - Burhinus oedicnemus",
              "speciesnameclean": "Burhinus oedicnemus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Reproducing",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/925/925_959.jpeg&x=300&y=300&a=true",
              "id_eunis": 925,
              "commonname": "Stone Curlew"
            }
          },
          {
            "attributes": {
              "objectid": 334009,
              "sitecode": "GR4210029",
              "speciescode": "A087",
              "speciesname": "Buteo buteo",
              "speciesname_label": "Buzzard - Buteo buteo",
              "speciesnameclean": "Buteo buteo",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Permanent, wintering",
              "population_type_1": "",
              "population_type_2": "Permanent",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/926/926_961.jpeg&x=300&y=300&a=true",
              "id_eunis": 926,
              "commonname": "Buzzard"
            }
          },
          {
            "attributes": {
              "objectid": 334010,
              "sitecode": "GR4210029",
              "speciescode": "A243",
              "speciesname": "Calandrella brachydactyla",
              "speciesname_label": "Short-toed Lark - Calandrella brachydactyla",
              "speciesnameclean": "Calandrella brachydactyla",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/929/929_964.jpeg&x=300&y=300&a=true",
              "id_eunis": 929,
              "commonname": "Short-toed Lark"
            }
          },
          {
            "attributes": {
              "objectid": 334011,
              "sitecode": "GR4210029",
              "speciescode": "A144",
              "speciesname": "Calidris alba",
              "speciesname_label": "Sanderling - Calidris alba",
              "speciesnameclean": "Calidris alba",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/933/933_967.jpeg&x=300&y=300&a=true",
              "id_eunis": 933,
              "commonname": "Sanderling"
            }
          },
          {
            "attributes": {
              "objectid": 334012,
              "sitecode": "GR4210029",
              "speciescode": "A149",
              "speciesname": "Calidris alpina",
              "speciesname_label": "Dunlin - Calidris alpina",
              "speciesnameclean": "Calidris alpina",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/934/934_968.jpeg&x=300&y=300&a=true",
              "id_eunis": 934,
              "commonname": "Dunlin"
            }
          },
          {
            "attributes": {
              "objectid": 334013,
              "sitecode": "GR4210029",
              "speciescode": "A147",
              "speciesname": "Calidris ferruginea",
              "speciesname_label": "Calidris ferruginea",
              "speciesnameclean": "Calidris ferruginea",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/936/936_973.jpeg&x=300&y=300&a=true",
              "id_eunis": 936,
              "commonname": ""
            }
          },
          {
            "attributes": {
              "objectid": 334014,
              "sitecode": "GR4210029",
              "speciescode": "A145",
              "speciesname": "Calidris minuta",
              "speciesname_label": "Little Stint - Calidris minuta",
              "speciesnameclean": "Calidris minuta",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/938/938_975.jpeg&x=300&y=300&a=true",
              "id_eunis": 938,
              "commonname": "Little Stint"
            }
          },
          {
            "attributes": {
              "objectid": 334015,
              "sitecode": "GR4210029",
              "speciescode": "A861",
              "speciesname": "Calidris pugnax",
              "speciesname_label": "Ruff - Calidris pugnax",
              "speciesnameclean": "Calidris pugnax",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1206/1206_11875.jpeg&x=300&y=300&a=true",
              "id_eunis": 320227,
              "commonname": "Ruff"
            }
          },
          {
            "attributes": {
              "objectid": 334016,
              "sitecode": "GR4210029",
              "speciescode": "A146",
              "speciesname": "Calidris temminckii",
              "speciesname_label": "Temminck's Stint - Calidris temminckii",
              "speciesnameclean": "Calidris temminckii",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/939/939_976.jpeg&x=300&y=300&a=true",
              "id_eunis": 939,
              "commonname": "Temminck's Stint"
            }
          },
          {
            "attributes": {
              "objectid": 334017,
              "sitecode": "GR4210029",
              "speciescode": "A224",
              "speciesname": "Caprimulgus europaeus",
              "speciesname_label": "Nightjar - Caprimulgus europaeus",
              "speciesnameclean": "Caprimulgus europaeus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Reproducing",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/941/941_984.jpeg&x=300&y=300&a=true",
              "id_eunis": 941,
              "commonname": "Nightjar"
            }
          },
          {
            "attributes": {
              "objectid": 334018,
              "sitecode": "GR4210029",
              "speciescode": "A138",
              "speciesname": "Charadrius alexandrinus",
              "speciesname_label": "Kentish Plover - Charadrius alexandrinus",
              "speciesnameclean": "Charadrius alexandrinus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, wintering",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/958/958_993.jpeg&x=300&y=300&a=true",
              "id_eunis": 958,
              "commonname": "Kentish Plover"
            }
          },
          {
            "attributes": {
              "objectid": 334022,
              "sitecode": "GR4210029",
              "speciescode": "A198",
              "speciesname": "Chlidonias leucopterus",
              "speciesname_label": "White-winged Black Tern - Chlidonias leucopterus",
              "speciesnameclean": "Chlidonias leucopterus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/966/966_1004.jpeg&x=300&y=300&a=true",
              "id_eunis": 966,
              "commonname": "White-winged Black Tern"
            }
          },
          {
            "attributes": {
              "objectid": 334023,
              "sitecode": "GR4210029",
              "speciescode": "A080",
              "speciesname": "Circaetus gallicus",
              "speciesname_label": "Short-toed Eagle - Circaetus gallicus",
              "speciesnameclean": "Circaetus gallicus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/972/972_1009.jpeg&x=300&y=300&a=true",
              "id_eunis": 972,
              "commonname": "Short-toed Eagle"
            }
          },
          {
            "attributes": {
              "objectid": 334024,
              "sitecode": "GR4210029",
              "speciescode": "A082",
              "speciesname": "Circus cyaneus",
              "speciesname_label": "Hen Harrier - Circus cyaneus",
              "speciesnameclean": "Circus cyaneus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/974/974_1015.jpeg&x=300&y=300&a=true",
              "id_eunis": 974,
              "commonname": "Hen Harrier"
            }
          },
          {
            "attributes": {
              "objectid": 334025,
              "sitecode": "GR4210029",
              "speciescode": "A083",
              "speciesname": "Circus macrourus",
              "speciesname_label": "Pallid Harrier - Circus macrourus",
              "speciesnameclean": "Circus macrourus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/975/975_1016.jpeg&x=300&y=300&a=true",
              "id_eunis": 975,
              "commonname": "Pallid Harrier"
            }
          },
          {
            "attributes": {
              "objectid": 334028,
              "sitecode": "GR4210029",
              "speciescode": "A859",
              "speciesname": "Clanga clanga",
              "speciesname_label": "Spotted Eagle - Clanga clanga",
              "speciesnameclean": "Clanga clanga",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Wintering",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/895/895_11871.jpeg&x=300&y=300&a=true",
              "id_eunis": 320230,
              "commonname": "Spotted Eagle"
            }
          },
          {
            "attributes": {
              "objectid": 334031,
              "sitecode": "GR4210029",
              "speciescode": "A113",
              "speciesname": "Coturnix coturnix",
              "speciesname_label": "Quail - Coturnix coturnix",
              "speciesnameclean": "Coturnix coturnix",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/994/994_1041.jpeg&x=300&y=300&a=true",
              "id_eunis": 994,
              "commonname": "Quail"
            }
          },
          {
            "attributes": {
              "objectid": 334032,
              "sitecode": "GR4210029",
              "speciescode": "A122",
              "speciesname": "Crex crex",
              "speciesname_label": "Corncrake - Crex crex",
              "speciesnameclean": "Crex crex",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/995/995_10073.jpeg&x=300&y=300&a=true",
              "id_eunis": 995,
              "commonname": "Corncrake"
            }
          },
          {
            "attributes": {
              "objectid": 334033,
              "sitecode": "GR4210029",
              "speciescode": "A212",
              "speciesname": "Cuculus canorus",
              "speciesname_label": "Cuckoo - Cuculus canorus",
              "speciesnameclean": "Cuculus canorus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/997/997_1043.jpeg&x=300&y=300&a=true",
              "id_eunis": 997,
              "commonname": "Cuckoo"
            }
          },
          {
            "attributes": {
              "objectid": 334034,
              "sitecode": "GR4210029",
              "speciescode": "A738",
              "speciesname": "Delichon urbicum",
              "speciesname_label": "Delichon urbicum",
              "speciesnameclean": "Delichon urbicum",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/320165/320165_4016.jpeg&x=300&y=300&a=true",
              "id_eunis": 320165,
              "commonname": ""
            }
          },
          {
            "attributes": {
              "objectid": 334035,
              "sitecode": "GR4210029",
              "speciescode": "A026",
              "speciesname": "Egretta garzetta",
              "speciesname_label": "Little Egret - Egretta garzetta",
              "speciesnameclean": "Egretta garzetta",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1016/1016_1053.jpeg&x=300&y=300&a=true",
              "id_eunis": 1016,
              "commonname": "Little Egret"
            }
          },
          {
            "attributes": {
              "objectid": 334036,
              "sitecode": "GR4210029",
              "speciescode": "A447",
              "speciesname": "Emberiza caesia",
              "speciesname_label": "Cretzschmar's Bunting - Emberiza caesia",
              "speciesnameclean": "Emberiza caesia",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Reproducing",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1018/1018_1055.jpeg&x=300&y=300&a=true",
              "id_eunis": 1018,
              "commonname": "Cretzschmar's Bunting"
            }
          },
          {
            "attributes": {
              "objectid": 334037,
              "sitecode": "GR4210029",
              "speciescode": "A100",
              "speciesname": "Falco eleonorae",
              "speciesname_label": "Eleonora's Falcon - Falco eleonorae",
              "speciesnameclean": "Falco eleonorae",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1035/1035_1072.jpeg&x=300&y=300&a=true",
              "id_eunis": 1035,
              "commonname": "Eleonora's Falcon"
            }
          },
          {
            "attributes": {
              "objectid": 334038,
              "sitecode": "GR4210029",
              "speciescode": "A103",
              "speciesname": "Falco peregrinus",
              "speciesname_label": "Peregrine - Falco peregrinus",
              "speciesnameclean": "Falco peregrinus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Permanent",
              "population_type_1": "",
              "population_type_2": "Permanent",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1038/1038_10026.jpeg&x=300&y=300&a=true",
              "id_eunis": 1038,
              "commonname": "Peregrine"
            }
          },
          {
            "attributes": {
              "objectid": 334039,
              "sitecode": "GR4210029",
              "speciescode": "A097",
              "speciesname": "Falco vespertinus",
              "speciesname_label": "Red-footed Falcon - Falco vespertinus",
              "speciesnameclean": "Falco vespertinus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1042/1042_1079.jpeg&x=300&y=300&a=true",
              "id_eunis": 1042,
              "commonname": "Red-footed Falcon"
            }
          },
          {
            "attributes": {
              "objectid": 334040,
              "sitecode": "GR4210029",
              "speciescode": "A321",
              "speciesname": "Ficedula albicollis",
              "speciesname_label": "Collared Flycatcher - Ficedula albicollis",
              "speciesnameclean": "Ficedula albicollis",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1043/1043_1080.jpeg&x=300&y=300&a=true",
              "id_eunis": 1043,
              "commonname": "Collared Flycatcher"
            }
          },
          {
            "attributes": {
              "objectid": 334041,
              "sitecode": "GR4210029",
              "speciescode": "A153",
              "speciesname": "Gallinago gallinago",
              "speciesname_label": "Snipe - Gallinago gallinago",
              "speciesnameclean": "Gallinago gallinago",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1057/1057_1105.jpeg&x=300&y=300&a=true",
              "id_eunis": 1057,
              "commonname": "Snipe"
            }
          },
          {
            "attributes": {
              "objectid": 334042,
              "sitecode": "GR4210029",
              "speciescode": "A131",
              "speciesname": "Himantopus himantopus",
              "speciesname_label": "Black-winged Stilt - Himantopus himantopus",
              "speciesnameclean": "Himantopus himantopus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1076/1076_10028.jpeg&x=300&y=300&a=true",
              "id_eunis": 1076,
              "commonname": "Black-winged Stilt"
            }
          },
          {
            "attributes": {
              "objectid": 334043,
              "sitecode": "GR4210029",
              "speciescode": "A439",
              "speciesname": "Hippolais olivetorum",
              "speciesname_label": "Olive-tree Warbler - Hippolais olivetorum",
              "speciesnameclean": "Hippolais olivetorum",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1078/1078_1135.jpeg&x=300&y=300&a=true",
              "id_eunis": 1078,
              "commonname": "Olive-tree Warbler"
            }
          },
          {
            "attributes": {
              "objectid": 334044,
              "sitecode": "GR4210029",
              "speciescode": "A251",
              "speciesname": "Hirundo rustica",
              "speciesname_label": "Swallow - Hirundo rustica",
              "speciesnameclean": "Hirundo rustica",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1083/1083_1143.jpeg&x=300&y=300&a=true",
              "id_eunis": 1083,
              "commonname": "Swallow"
            }
          },
          {
            "attributes": {
              "objectid": 334045,
              "sitecode": "GR4210029",
              "speciescode": "A862",
              "speciesname": "Hydrocoloeus minutus",
              "speciesname_label": "Hydrocoloeus minutus",
              "speciesnameclean": "Hydrocoloeus minutus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://eunis.eea.europa.eu/images/species/320163/thumbnail.jpg",
              "id_eunis": 320163,
              "commonname": ""
            }
          },
          {
            "attributes": {
              "objectid": 334046,
              "sitecode": "GR4210029",
              "speciescode": "A022",
              "speciesname": "Ixobrychus minutus",
              "speciesname_label": "Little Bittern - Ixobrychus minutus",
              "speciesnameclean": "Ixobrychus minutus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1090/1090_1147.jpeg&x=300&y=300&a=true",
              "id_eunis": 1090,
              "commonname": "Little Bittern"
            }
          },
          {
            "attributes": {
              "objectid": 334047,
              "sitecode": "GR4210029",
              "speciescode": "A233",
              "speciesname": "Jynx torquilla",
              "speciesname_label": "Wryneck - Jynx torquilla",
              "speciesnameclean": "Jynx torquilla",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1091/1091_1148.jpeg&x=300&y=300&a=true",
              "id_eunis": 1091,
              "commonname": "Wryneck"
            }
          },
          {
            "attributes": {
              "objectid": 334048,
              "sitecode": "GR4210029",
              "speciescode": "A339",
              "speciesname": "Lanius minor",
              "speciesname_label": "Lesser Grey Shrike - Lanius minor",
              "speciesnameclean": "Lanius minor",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1100/1100_1157.jpeg&x=300&y=300&a=true",
              "id_eunis": 1100,
              "commonname": "Lesser Grey Shrike"
            }
          },
          {
            "attributes": {
              "objectid": 334051,
              "sitecode": "GR4210029",
              "speciescode": "A179",
              "speciesname": "Larus ridibundus",
              "speciesname_label": "Black-headed Gull - Larus ridibundus",
              "speciesnameclean": "Larus ridibundus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Wintering",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1115/1115_4211.jpeg&x=300&y=300&a=true",
              "id_eunis": 1115,
              "commonname": "Black-headed Gull"
            }
          },
          {
            "attributes": {
              "objectid": 334052,
              "sitecode": "GR4210029",
              "speciescode": "A156",
              "speciesname": "Limosa limosa",
              "speciesname_label": "Black-tailed Godwit - Limosa limosa",
              "speciesnameclean": "Limosa limosa",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1119/1119_1173.jpeg&x=300&y=300&a=true",
              "id_eunis": 1119,
              "commonname": "Black-tailed Godwit"
            }
          },
          {
            "attributes": {
              "objectid": 334053,
              "sitecode": "GR4210029",
              "speciescode": "A246",
              "speciesname": "Lullula arborea",
              "speciesname_label": "Woodlark - Lullula arborea",
              "speciesnameclean": "Lullula arborea",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Permanent, reproducing",
              "population_type_1": "",
              "population_type_2": "Permanent",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1126/1126_10030.jpeg&x=300&y=300&a=true",
              "id_eunis": 1126,
              "commonname": "Woodlark"
            }
          },
          {
            "attributes": {
              "objectid": 334054,
              "sitecode": "GR4210029",
              "speciescode": "A230",
              "speciesname": "Merops apiaster",
              "speciesname_label": "Bee-eater - Merops apiaster",
              "speciesnameclean": "Merops apiaster",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1141/1141_1214.jpeg&x=300&y=300&a=true",
              "id_eunis": 1141,
              "commonname": "Bee-eater"
            }
          },
          {
            "attributes": {
              "objectid": 334055,
              "sitecode": "GR4210029",
              "speciescode": "A260",
              "speciesname": "Motacilla flava",
              "speciesname_label": "Yellow Wagtail - Motacilla flava",
              "speciesnameclean": "Motacilla flava",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1151/1151_1231.jpeg&x=300&y=300&a=true",
              "id_eunis": 1151,
              "commonname": "Yellow Wagtail"
            }
          },
          {
            "attributes": {
              "objectid": 334056,
              "sitecode": "GR4210029",
              "speciescode": "A768",
              "speciesname": "Numenius arquata arquata",
              "speciesname_label": "Numenius arquata arquata",
              "speciesnameclean": "Numenius arquata arquata",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": null,
              "id_eunis": 437275,
              "commonname": ""
            }
          },
          {
            "attributes": {
              "objectid": 334060,
              "sitecode": "GR4210029",
              "speciescode": "A023",
              "speciesname": "Nycticorax nycticorax",
              "speciesname_label": "Night Heron - Nycticorax nycticorax",
              "speciesnameclean": "Nycticorax nycticorax",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1162/1162_10035.jpeg&x=300&y=300&a=true",
              "id_eunis": 1162,
              "commonname": "Night Heron"
            }
          },
          {
            "attributes": {
              "objectid": 334063,
              "sitecode": "GR4210029",
              "speciescode": "A337",
              "speciesname": "Oriolus oriolus",
              "speciesname_label": "Golden Oriole - Oriolus oriolus",
              "speciesnameclean": "Oriolus oriolus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1170/1170_1246.jpeg&x=300&y=300&a=true",
              "id_eunis": 1170,
              "commonname": "Golden Oriole"
            }
          },
          {
            "attributes": {
              "objectid": 334064,
              "sitecode": "GR4210029",
              "speciescode": "A094",
              "speciesname": "Pandion haliaetus",
              "speciesname_label": "Osprey - Pandion haliaetus",
              "speciesnameclean": "Pandion haliaetus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1176/1176_1252.jpeg&x=300&y=300&a=true",
              "id_eunis": 1176,
              "commonname": "Osprey"
            }
          },
          {
            "attributes": {
              "objectid": 334065,
              "sitecode": "GR4210029",
              "speciescode": "A355",
              "speciesname": "Passer hispaniolensis",
              "speciesname_label": "Spanish Sparrow - Passer hispaniolensis",
              "speciesnameclean": "Passer hispaniolensis",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1186/1186_1255.jpeg&x=300&y=300&a=true",
              "id_eunis": 1186,
              "commonname": "Spanish Sparrow"
            }
          },
          {
            "attributes": {
              "objectid": 334066,
              "sitecode": "GR4210029",
              "speciescode": "A072",
              "speciesname": "Pernis apivorus",
              "speciesname_label": "Honey Buzzard - Pernis apivorus",
              "speciesnameclean": "Pernis apivorus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1195/1195_10038.jpeg&x=300&y=300&a=true",
              "id_eunis": 1195,
              "commonname": "Honey Buzzard"
            }
          },
          {
            "attributes": {
              "objectid": 334067,
              "sitecode": "GR4210029",
              "speciescode": "A392",
              "speciesname": "Phalacrocorax aristotelis desmarestii",
              "speciesname_label": "Shag (Mediterranean subspecies) - Phalacrocorax aristotelis desmarestii",
              "speciesnameclean": "Phalacrocorax aristotelis desmarestii",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Permanent",
              "population_type_1": "",
              "population_type_2": "Permanent",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": null,
              "id_eunis": 1199,
              "commonname": "Shag (Mediterranean subspecies)"
            }
          },
          {
            "attributes": {
              "objectid": 334068,
              "sitecode": "GR4210029",
              "speciescode": "A391",
              "speciesname": "Phalacrocorax carbo sinensis",
              "speciesname_label": "Cormorant (continental subspecies) - Phalacrocorax carbo sinensis",
              "speciesnameclean": "Phalacrocorax carbo sinensis",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Wintering",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": null,
              "id_eunis": 1201,
              "commonname": "Cormorant (continental subspecies)"
            }
          },
          {
            "attributes": {
              "objectid": 334069,
              "sitecode": "GR4210029",
              "speciescode": "A141",
              "speciesname": "Pluvialis squatarola",
              "speciesname_label": "Grey Plover - Pluvialis squatarola",
              "speciesnameclean": "Pluvialis squatarola",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1224/1224_1288.jpeg&x=300&y=300&a=true",
              "id_eunis": 1224,
              "commonname": "Grey Plover"
            }
          },
          {
            "attributes": {
              "objectid": 334070,
              "sitecode": "GR4210029",
              "speciescode": "A005",
              "speciesname": "Podiceps cristatus",
              "speciesname_label": "Great Crested Grebe - Podiceps cristatus",
              "speciesnameclean": "Podiceps cristatus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Wintering",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1226/1226_11259.jpeg&x=300&y=300&a=true",
              "id_eunis": 1226,
              "commonname": "Great Crested Grebe"
            }
          },
          {
            "attributes": {
              "objectid": 334071,
              "sitecode": "GR4210029",
              "speciescode": "A008",
              "speciesname": "Podiceps nigricollis",
              "speciesname_label": "Black-necked Grebe - Podiceps nigricollis",
              "speciesnameclean": "Podiceps nigricollis",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Wintering",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1228/1228_1294.jpeg&x=300&y=300&a=true",
              "id_eunis": 1228,
              "commonname": "Black-necked Grebe"
            }
          },
          {
            "attributes": {
              "objectid": 334072,
              "sitecode": "GR4210029",
              "speciescode": "A119",
              "speciesname": "Porzana porzana",
              "speciesname_label": "Spotted Crake - Porzana porzana",
              "speciesnameclean": "Porzana porzana",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1232/1232_1296.jpeg&x=300&y=300&a=true",
              "id_eunis": 1232,
              "commonname": "Spotted Crake"
            }
          },
          {
            "attributes": {
              "objectid": 334073,
              "sitecode": "GR4210029",
              "speciescode": "A249",
              "speciesname": "Riparia riparia",
              "speciesname_label": "Sand Martin - Riparia riparia",
              "speciesnameclean": "Riparia riparia",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1260/1260_1326.jpeg&x=300&y=300&a=true",
              "id_eunis": 1260,
              "commonname": "Sand Martin"
            }
          },
          {
            "attributes": {
              "objectid": 334074,
              "sitecode": "GR4210029",
              "speciescode": "A193",
              "speciesname": "Sterna hirundo",
              "speciesname_label": "Common Tern - Sterna hirundo",
              "speciesnameclean": "Sterna hirundo",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1282/1282_10043.jpeg&x=300&y=300&a=true",
              "id_eunis": 1282,
              "commonname": "Common Tern"
            }
          },
          {
            "attributes": {
              "objectid": 334075,
              "sitecode": "GR4210029",
              "speciescode": "A885",
              "speciesname": "Sternula albifrons",
              "speciesname_label": "Sternula albifrons",
              "speciesnameclean": "Sternula albifrons",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://eunis.eea.europa.eu/images/species/320164/thumbnail.jpg",
              "id_eunis": 320164,
              "commonname": ""
            }
          },
          {
            "attributes": {
              "objectid": 334076,
              "sitecode": "GR4210029",
              "speciescode": "A210",
              "speciesname": "Streptopelia turtur",
              "speciesname_label": "Turtle Dove - Streptopelia turtur",
              "speciesnameclean": "Streptopelia turtur",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1286/1286_1360.jpeg&x=300&y=300&a=true",
              "id_eunis": 1286,
              "commonname": "Turtle Dove"
            }
          },
          {
            "attributes": {
              "objectid": 334077,
              "sitecode": "GR4210029",
              "speciescode": "A440",
              "speciesname": "Sylvia ruppeli",
              "speciesname_label": "Rüppell's Warbler - Sylvia ruppeli",
              "speciesnameclean": "Sylvia ruppeli",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Reproducing",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1304/1304_1378.jpeg&x=300&y=300&a=true",
              "id_eunis": 1304,
              "commonname": "Rüppell's Warbler"
            }
          },
          {
            "attributes": {
              "objectid": 334078,
              "sitecode": "GR4210029",
              "speciescode": "A228",
              "speciesname": "Tachymarptis melba",
              "speciesname_label": "Alpine Swift - Tachymarptis melba",
              "speciesnameclean": "Tachymarptis melba",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, reproducing",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "Reproducing",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1308/1308_1389.jpeg&x=300&y=300&a=true",
              "id_eunis": 1308,
              "commonname": "Alpine Swift"
            }
          },
          {
            "attributes": {
              "objectid": 334079,
              "sitecode": "GR4210029",
              "speciescode": "A161",
              "speciesname": "Tringa erythropus",
              "speciesname_label": "Spotted Redshank - Tringa erythropus",
              "speciesnameclean": "Tringa erythropus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1320/1320_1397.jpeg&x=300&y=300&a=true",
              "id_eunis": 1320,
              "commonname": "Spotted Redshank"
            }
          },
          {
            "attributes": {
              "objectid": 334080,
              "sitecode": "GR4210029",
              "speciescode": "A166",
              "speciesname": "Tringa glareola",
              "speciesname_label": "Wood Sandpiper - Tringa glareola",
              "speciesnameclean": "Tringa glareola",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1321/1321_1398.jpeg&x=300&y=300&a=true",
              "id_eunis": 1321,
              "commonname": "Wood Sandpiper"
            }
          },
          {
            "attributes": {
              "objectid": 334081,
              "sitecode": "GR4210029",
              "speciescode": "A164",
              "speciesname": "Tringa nebularia",
              "speciesname_label": "Greenshank - Tringa nebularia",
              "speciesnameclean": "Tringa nebularia",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, wintering",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1323/1323_1399.jpeg&x=300&y=300&a=true",
              "id_eunis": 1323,
              "commonname": "Greenshank"
            }
          },
          {
            "attributes": {
              "objectid": 334082,
              "sitecode": "GR4210029",
              "speciescode": "A165",
              "speciesname": "Tringa ochropus",
              "speciesname_label": "Green Sandpiper - Tringa ochropus",
              "speciesnameclean": "Tringa ochropus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Wintering",
              "population_type_1": "",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1324/1324_1401.jpeg&x=300&y=300&a=true",
              "id_eunis": 1324,
              "commonname": "Green Sandpiper"
            }
          },
          {
            "attributes": {
              "objectid": 334083,
              "sitecode": "GR4210029",
              "speciescode": "A163",
              "speciesname": "Tringa stagnatilis",
              "speciesname_label": "Marsh Sandpiper - Tringa stagnatilis",
              "speciesnameclean": "Tringa stagnatilis",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1325/1325_1402.jpeg&x=300&y=300&a=true",
              "id_eunis": 1325,
              "commonname": "Marsh Sandpiper"
            }
          },
          {
            "attributes": {
              "objectid": 334084,
              "sitecode": "GR4210029",
              "speciescode": "A162",
              "speciesname": "Tringa totanus",
              "speciesname_label": "Redshank - Tringa totanus",
              "speciesnameclean": "Tringa totanus",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration, wintering",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "Wintering",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1326/1326_1403.jpeg&x=300&y=300&a=true",
              "id_eunis": 1326,
              "commonname": "Redshank"
            }
          },
          {
            "attributes": {
              "objectid": 334085,
              "sitecode": "GR4210029",
              "speciescode": "A892",
              "speciesname": "Zapornia parva",
              "speciesname_label": "Little Crake - Zapornia parva",
              "speciesnameclean": "Zapornia parva",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1231/1231_11894.jpeg&x=300&y=300&a=true",
              "id_eunis": 320224,
              "commonname": "Little Crake"
            }
          },
          {
            "attributes": {
              "objectid": 334086,
              "sitecode": "GR4210029",
              "speciescode": "A893",
              "speciesname": "Zapornia pusilla",
              "speciesname_label": "Baillon's Crake - Zapornia pusilla",
              "speciesnameclean": "Zapornia pusilla",
              "sptype": "B",
              "sptype_label": "Birds",
              "population_type_label": "Concentration",
              "population_type_1": "Concentration",
              "population_type_2": "",
              "population_type_3": "",
              "population_type_4": "",
              "countrycode": "GR",
              "country": "Greece",
              "bioregion": " Mediterranean",
              "bioregion_code": " mediterranean",
              "species_image_url": "https://cmshare.eea.europa.eu/apps/files_sharing/publicpreview/mj7RixbbaNbQZPd?file=/Species/Web/1233/1233_11895.jpeg&x=300&y=300&a=true",
              "id_eunis": 320225,
              "commonname": "Baillon's Crake"
            }
          }
        ]
      }
    ]
  }

const data = dataArray.layers[0].features


// console.log((data))

let sample = ``

for(let i = 0; i < data.length; i++){
  sample += `
  <div class="inner-container">
    <img src="${data[i].attributes.species_image_url}" />
    <div class="container-txt">
      <ul>
      <li><span>Species Type Label: </span>${data[i].attributes.sptype_label}</li>
      <li><span> Species Type: </span>${data[i].attributes.sptype}</li>
      <li><span>Species Name: </span>${data[i].attributes.speciesname}</li>
      <li><span>Bioregion: </span>${data[i].attributes.bioregion}</li>
      <li><span>Common Name: </span>${data[i].attributes.commonname}</li>
      <li><span>Population Type Label: </span>${data[i].attributes.population_type_label}</li>
      <li><span>Country: </span>${data[i].attributes.country}</li>
      <li><span>Species Code: </span>${data[i].attributes.speciescode}</li>
      </ul>
    </div>
  </div>
  `
}

const container = document.querySelector('.container')
container.innerHTML += `${sample}`
